version: '3.7'
services:
  nginx:
    image: nginx:1.15.9-alpine
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./public:/usr/share/nginx/html"
    ports:
      - "80:80"
  node:
    image: node:10.15.2
    command: ["node", "dist/main.js"]
    working_dir: /app
    volumes:
      - ".:/app"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://chat:password@mongo:27017/test
  mongo:
    image: mongo:4.0.6
    volumes:
      - "./docker/mongo/initdb:/docker-entrypoint-initdb.d"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
